x-uffizzi:
  ingress:
    service: app
    port: 80
  continuous_previews:
    delete_preview_after: 1h

services:
  app:
    image: ghcr.io/kamanorga/uffizzi:latest
    ports:
      - "80:8080"
    deploy:
      resources:
        limits:
          memory: 512M
